# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `simplecov-console` gem.
# Please instead update this file by running `bin/tapioca gem simplecov-console`.


# source://simplecov-console//lib/simplecov-console.rb#3
class SimpleCov::Formatter::Console
  # source://simplecov-console//lib/simplecov-console.rb#120
  def branches_missed(missed_branches); end

  # source://simplecov-console//lib/simplecov-console.rb#184
  def colorize(s); end

  # source://simplecov-console//lib/simplecov-console.rb#50
  def format(result); end

  # source://simplecov-console//lib/simplecov-console.rb#34
  def include_output_style; end

  # Group missed lines for better display
  #
  # @param missed [Array<SimpleCov::SourceFile::Line>] array of missed lines reported by SimpleCov
  # @return [Array<String>] Missing groups of lines
  #
  # source://simplecov-console//lib/simplecov-console.rb#131
  def missed(missed_lines); end

  # source://simplecov-console//lib/simplecov-console.rb#176
  def pct(number); end

  # @return [Boolean]
  #
  # source://simplecov-console//lib/simplecov-console.rb#45
  def show_branch_coverage?(result); end

  # Truncate string to at most N chars (as defined by missing_len)
  #
  # source://simplecov-console//lib/simplecov-console.rb#166
  def trunc(str); end

  # @return [Boolean]
  #
  # source://simplecov-console//lib/simplecov-console.rb#180
  def use_colors?; end

  class << self
    # source://simplecov-console//lib/simplecov-console.rb#11
    def max_lines; end

    # source://simplecov-console//lib/simplecov-console.rb#11
    def max_lines=(_arg0); end

    # source://simplecov-console//lib/simplecov-console.rb#11
    def max_rows; end

    # source://simplecov-console//lib/simplecov-console.rb#11
    def max_rows=(_arg0); end

    # source://simplecov-console//lib/simplecov-console.rb#11
    def missing_len; end

    # source://simplecov-console//lib/simplecov-console.rb#11
    def missing_len=(_arg0); end

    # source://simplecov-console//lib/simplecov-console.rb#11
    def output_style; end

    # source://simplecov-console//lib/simplecov-console.rb#11
    def output_style=(_arg0); end

    # source://simplecov-console//lib/simplecov-console.rb#11
    def show_covered; end

    # source://simplecov-console//lib/simplecov-console.rb#11
    def show_covered=(_arg0); end

    # source://simplecov-console//lib/simplecov-console.rb#11
    def sort; end

    # source://simplecov-console//lib/simplecov-console.rb#11
    def sort=(_arg0); end

    # source://simplecov-console//lib/simplecov-console.rb#11
    def table_options; end

    # source://simplecov-console//lib/simplecov-console.rb#11
    def table_options=(_arg0); end

    # source://simplecov-console//lib/simplecov-console.rb#11
    def use_colors; end

    # source://simplecov-console//lib/simplecov-console.rb#11
    def use_colors=(_arg0); end
  end
end

# source://simplecov-console//lib/simplecov-console.rb#7
SimpleCov::Formatter::Console::ATTRIBUTES = T.let(T.unsafe(nil), Array)

# source://simplecov-console//lib/simplecov-console.rb#5
SimpleCov::Formatter::Console::VERSION = T.let(T.unsafe(nil), String)
