require:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-sorbet

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - bin/*
    - vendor/bundle/**/*
    - '*.gemspec'
    - tmp/*

Layout/LineLength:
  Max: 125

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Max: 30

Metrics/ClassLength:
  Max: 150

RSpec/ExampleLength:
  Max: 25

Metrics/MethodLength:
  Max: 30

RSpec/MultipleMemoizedHelpers:
  Max: 10
